### ISSUE TITLE
Protótipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#14]
**Descrição**
Elaborar um Protótipo de Baixa Fidelidade para o aplicativo e levantar feedbacks.

**Tasks**
 * [x] Protótipo de de baixa fidelidade finalizado
 * [x] Feedback  - Daniel
 * [x] Feedback  - Pedro
 * [x] Feedback  - Luís
 * [x] Feedback  - Cauê
 * [x] Feedback  - Lucas

**Critérios de Aceitação**
 * [x] Adicionar Referência
 * [x] Adicionar na Wiki

**Comment by lbrunofidelis** [comment]
Analisado e finalizado.
