### ISSUE TITLE
Diagrama Causa-Efeito

### ISSUE THREAD

**Issue by lbrunofidelis** [UnBPaquera/Wiki#18]
**Descrição**
Elaborar diagrama Causa-Efeito.

**Tasks**
 * [ ] Diagrama Causa-Efeito

**Critérios de Aceitação**
 * [ ] Adicionar Referência
 * [ ] Adicionar na wiki

**Comment by lbrunofidelis** [comment]
Dívida técnica para Sprint 3.

**Comment by tmcstiago** [comment]
Foi mostrado que este diagrama não se enquadra nesta estapa do projeto

**Comment by dansousamelo** [comment]
Issue cancelada.
