### ISSUE TITLE
Protótipo de Média Fidelidade Versão I

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#24]
**Descrição**
Elaborar o Protótipo de Média Fidelidade

**Tasks**
 * [x] Conter todas as funcionalidades levantadas

**Critérios de Aceitação**
 * [x] Adicionar Referência
 * [x] Adicionar na Wiki

**Comment by lbrunofidelis** [comment]
Versão 1 do protótipo finalizada disponível em https://whimsical.com/WqgXeGdgcV7oMZxgc7vz8t
