### ISSUE TITLE
Técnica de Elicitação - 6 chapéus

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#3]
**Descrição**
As duas equipes devem se juntar para a realização da técnica dos 6 chapéus.

**Tasks**
 * [x] Levantar requisitos surpresas, principalmente.

**Critérios de Aceitação**
 * [x] Adicionar Referência
 * [x] Colocar o documento em Markdown

**Comment by dansousamelo** [comment]
Não foi atingido o número considerado de pessoas

**Comment by lbrunofidelis** [comment]
Finalizado
